### ISSUE TITLE
Lint step for slug length

### ISSUE THREAD

**Issue by piatra** [mozilla/messaging-system-inflight-assets#114]
Trying to get a dashboard for the containers experiment I noticed that the slug is truncated at 80 chars. It took a while to figure it out. Publish time seems a good place to warn/prevent wdyt @ncloudioj?

**Comment by ncloudioj** [comment]
That's a good idea.

I believe Experimenter should've enforced it, hasn't it? If so, we should be fine if we only copy slug from there.

**Comment by piatra** [comment]
Good point, it is enforced in experimenter I'll keep count of that in the future.
