### ISSUE TITLE
Issues with the new experiment schema

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/messaging-system-inflight-assets#149]
While trying to get the first-run experiment to pass the new schema in this [patch](https://github.com/AllegroFox/messaging-system-inflight-assets/commit/7eef285c27925d8ae040256ba575a7d30c4f196a), we've run into the following observations/validation errors:

* The new schema doesn't allow `id`, `targeting`, and `filter_expresion` which are all necessary as:
  - `id` is used as the ID for each record in RS, also the validation script [assumes](https://github.com/mozilla/messaging-system-inflight-assets/blob/master/scripts/validate.py#L205) it's a required field for each item
  - `targeting` is used by x-man
  - `filter_expresion` is used for server-side filtering by RS
* The deletion of `arguments`, which is just a minor issue. We just need to update the validation script [here](https://github.com/mozilla/messaging-system-inflight-assets/blob/master/scripts/validate.py#L206) so it can check the recipe with the same schema
* How we populate those following required fields in the new schema:
  - startDate
  - endDate
  - proposedDuration
  - proposedEnrollment
  - referenceBranch

**Comment by ncloudioj** [comment]
Looks like xman in Fx 82 remains the same (as to how it expects the experiment recipe), and the only change is that `RemosettingsExperimentloader` will be using the new RS collection. My understanding is that we probably would stick to the old schema until the new schema gets integrated into xman. We might want to communicate with the nimbus team about this as we will be publishing schema incompatible stuff to RS. 

Does that make sense? @piatra

**Comment by piatra** [comment]
I don't think we should use the old schema. Making such exceptions will most likely cause problems in the future with validation. I think we should start fresh with the new bucket.
I think the schema issue was a mistake on my part for copying the wrong file from nimbus-shared. I've opened a pull request. It's a little tricky because there wasn't anything to validate against.
