### ISSUE TITLE
Ensure the message naming convention for the CFR experiments

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/messaging-system-inflight-assets#159]
This allows Jetstream to perform the automated analysis, which requires messages of CFR experiments to use the branch slug as the message ID.

**Comment by k88hudson** [comment]
Can we make sure this includes both experiment and branch slug?

**Comment by ncloudioj** [comment]
Sure, any particular requirement on the separator between the two, like ":" or "/"?

**Comment by k88hudson** [comment]
unless @tdsmith has a preference i think `:` is fine
