### ISSUE TITLE
Review and add CFR recipe for Firefox Better Web

### ISSUE THREAD

**Issue by raymak** [mozilla/messaging-system-inflight-assets#36]
I have created a recipe for a recommendation sending users to the landing page of FBW:
https://gist.github.com/raymak/f5f21f0903b50bd1c9087e8fd7ff144e

I'd like to have it reviewed. The specs are documented here: https://docs.google.com/document/d/1jOECBfl3dDtnlpZuZlpWwi6eh8KWjG4bgUYe7U8RrFc/edit#

In particular two fields are missing: “icon” (which needs the icon) and “last_modified” (I’m not sure what it is, is that automatically generated?), also not so sure about the “cohort” field in “targeting”. 

Can the icon url be a remote url or does the icon have to be stored on the client?

**Comment by piatra** [comment]
* for `icon` the provided url is enough, we can include it as base64
* `last_modified` is only a Remote Settings internal detail that does not need to be submitted
* `cohort` is an implementation detail of the experiment targeting

The targeting details (What types of user behaviors would lead to showing the recommendation?) seems ok to me, I'll give a more thorough review and publish a message tomorrow.

Some follow up questions:
* Should this go out to 100% of the users that qualify?
* When should this go out?

**Comment by raymak** [comment]
I'll get back to you on the follow up questions. But first have another question. Do we have the ability to ramp up in stages? For instance start at 20% then look at the numbers and ramp up only if necessary?

**Comment by piatra** [comment]
Yes. We can have a monitoring dashboard for impression, click, dismiss actions as soon as the message goes up. Going from 20% to more means adjusting the targeting expression on the message and the update cycle for the clients is 1 hour so we can have quick feedback.
Is that ok?

**Comment by piatra** [comment]
<img width="162" alt="image" src="https://user-images.githubusercontent.com/810040/80518019-737d6c80-8975-11ea-82be-2ca4c59f0bfb.png">

<img width="407" alt="image" src="https://user-images.githubusercontent.com/810040/80519020-d6bbce80-8976-11ea-9ec2-e107f0649a5c.png">
