### ISSUE TITLE
Add import script from experimenter

### ISSUE THREAD

**Issue by k88hudson** [mozilla/messaging-system-inflight-assets#60]
Given an `experimenterSlug`, URL format is as follows:

https://experimenter.services.mozilla.com/api/v1/experiments/${experimenterSlug}/recipe/

The part that we would create the messaging experiment from would be the `arguments` property on the response.

Example: https://experimenter.services.mozilla.com/api/v1/experiments/recommend-picture-in-picture-cfr-normandy/recipe/

**Comment by piatra** [comment]
I can work on this.
